# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    error_controller: 'twig.controller.exception:showAction' # Adjust or remove if not needed
    serializer:
        enabled: true
    session:
        handler_id: null
        cookie_secure: auto
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
    validation:
        enabled: true # Enable the validation component
        enable_attributes: true # Use PHP attributes (if applicable)
    # Other framework options...



when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file



   